version = "1.0"

[main]
name.en = "Streams configuration"
name.fr = "Configuration de Streams"

    [main.php_fpm_config]
    name.en = "PHP-FPM configuration"
    name.fr = "Configuration de PHP-FPM"

        [main.php_fpm_config.fpm_footprint]
        ask.en = "Memory footprint"
        ask.fr = "Empreinte mémoire"
        type = "select"
        choices.low.en = "Low, <= 20Mb per pool"
        choices.low.fr = "Basse, <= 20Mb par pool"
        choices.medium.en = "Medium, between 20Mb and 40Mb par pool"
        choices.medium.fr = "Moyenne, entre 20Mb et 40Mb par pool"
        choices.high.en = "High, > 40Mb per pool"
        choices.high.fr = "Haute, > 40Mb par pool"
        choices.specific.en = "Use specific value"
        choices.specific.fr = "Utiliser une valeur précise"
        default = "medium"

        [main.php_fpm_config.fpm_free_footprint]
        visible = "fpm_footprint == 'specific'"
        ask.en = "Memory footprint of the service?"
        ask.fr = "Empreinte mémoire du service?"
        type = "number"
        default = "0"
        help.en = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."
        help.fr = "Champ libre pour spécifier exactement l'empreinte mémoire en Mb si vous ne souhaitez pas utiliser l'une des trois valeurs précédentes."

        [main.php_fpm_config.fpm_usage]
        ask.en = "Expected usage"
        ask.fr = "Utilisation prévue"
        type = "select"
        choices.low.en = "Low"
        choices.low.fr = "Minime"
        choices.medium.en = "Medium"
        choices.medium.fr = "Moyenne"
        choices.high.en = "High"
        choices.high.fr = "Intensive"
        default = "medium"
        help.en = "<strong>Low</strong>: Personal usage, behind the SSO. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br><strong>Medium</strong>: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br><strong>High</strong>: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
        help.fr = "<strong>Faible</strong> : Utilisation personnelle, derrière le SSO. Pas d'empreinte RAM en cas de non-utilisation, mais l'impact sur le processeur peut être élevé si de nombreux utilisateurs utilisent le service.<br><strong>Moyenne</strong> : Faible utilisation, peu d'utilisateurs et/ou service pas nécessairement accessible au public. Faible empreinte RAM, empreinte moyenne sur le processeur en cas d'utilisation.<br><strong>Intensive</strong> : Utilisation soutenue, site web fréquemment visité. L'empreinte RAM est élevée, mais l'utilisation du processeur est moindre et le service répond rapidement."
