#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "forte"
name = "Forte"
description.en = "open source ActivityPub/fediverse server"
description.fr = "Serveur ActivityPub/fediverse open source"

version = "25.9.3~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Unlicense"
code = "https://codeberg.org/fortified/forte"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "150M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    help.en = "Your website can only be installed in a root domain or subdomain"
    help.fr = "Votre site web ne peut être installé que dans un domaine racine ou un sous-domaine"
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.activate_directory]
    ask.en = "Do you want to activate the directory?"
    ask.fr = "Voulez-vous activer l'annuaire ?"
    help.en = "The site directory and friends suggestions are populated importing 'friends of friends' from connections that are made on your site. You might wish to disable this if your server has limited resources. This can be changed later in your website's Admin interface."
    help.fr = "L'annuaire du site et les suggestions d'amis sont alimentés par l'importation des 'amis d'amis' à partir des connexions établies sur votre site. Vous pouvez désactiver cette fonction si votre serveur dispose de ressources limitées. Ce réglage peut être modifié ultérieurement dans l'interface d'administration de votre site."
    type = "boolean"
    default = true

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://codeberg.org/fortified/forte/archive/v25.9.3.tar.gz"
    sha256 = "86cde178abbb5778c99e963607b7c2bc71adef1312b02a0eeb333e360b06e3bd"

    autoupdate.strategy = "latest_forgejo_tag"
    autoupdate.version_regex = "^v(.*)$"

    [resources.sources.addons]
    url = "https://codeberg.org/fortified/forte-addons/archive/v25.8.22.tar.gz"
    sha256 = "c84661a6df7acbace8ac8be6481e8c786e280f2c280b0e6353103f217cf41b7f"
    autoupdate.upstream = "https://codeberg.org/fortified/forte-addons"
    autoupdate.strategy = "latest_forgejo_tag"
    autoupdate.version_regex = "^v(.*)$"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "php8.4-mbstring, php8.4-cli, php8.4-imagick, php8.4-xml, php8.4-zip, php8.4-curl, php8.4-ldap, php8.4-gd, mariadb-server, php8.4-mysql php8.4-gmp"

    [resources.database]
    type = "mysql"

    [resources.composer]
    version = "2.8.11"
