packaging_format = 2

id = "streams"
name = "Streams"
description.en = "Open source fediverse server"
description.fr = "Serveur fediverse open source"

version = "23.12.17~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Unlicense"
code = "https://codeberg.org/streams/streams"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "150M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    help.en = "Your website can only be installed in a root domain or subdomain"
    help.fr = "Votre site web ne peut être installé que dans un domaine racine ou un sous-domaine"
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-mbstring, php8.2-cli, php8.2-imagick, php8.2-xml, php8.2-zip, php8.2-curl, php8.2-ldap, php8.2-gd, mariadb-server, php8.2-mysql php8.2-gmp"

    [resources.database]
    type = "mysql"
