packaging_format = 2

id = "streams"
name = "Streams"
description.en = "An open source fediverse server"
description.fr = "Un serveur fediverse open source"

version = "23.07.30~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Public Domain"
website = ""
code = "https://codeberg.org/streams/streams"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = true
sso = true
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.database]
    ask.en = "Choose your database"
    ask.fr = "Choisissez votre base de données"
    type = "string"
    choices = ["mysql", "postgresql"]
    default = "mysql"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://codeberg.org/streams/streams/archive/b7db8b66261fa6a18dc59890d5461c2fb85242fa.tar.gz"
        sha256 = "adf9e6a18cdea8df8dd22fb35afc201c2a8660327c055ef445fbae89190d8df1"

        [resources.sources.addons]
        url = "https://codeberg.org/streams/streams-addons/archive/0ff7cafbb205611c9f5fbbb8d8294c0b9dba0d70.tar.gz"
        sha256 = "2118bb796e1113a50b72c525708484563656edfe4b03c50b01ef973d839f3bce"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-mbstring php8.2-cli php8.2-imagick php8.2-xml php8.2-zip php8.2-curl php8.2-ldap php8.2-json php8.2-gd"

    packages_from_raw_bash = """
            if [[ "$database" == "mysql" ]]; then 
                echo "mariadb-server php8.2-mysql"
            elif [[ "$database" == "postgresql" ]]; then 
                echo "postgresql postgresql-contrib php8.2-pgsql"
            fi
        """
