packaging_format = 2

id = "streams"
name = "Streams"
description.en = "Open source fediverse server"
description.fr = "Serveur fediverse open source"

version = "23.10.20~ynh1"

maintainers = ["Papa Dragon"]

[upstream]
license = "Unlicense"
code = "https://codeberg.org/streams/streams"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "150M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.domain]
    help.en = "Your website can only be installed in a root domain or subdomain"
    help.fr = "Votre site web ne peut être installé que dans un domaine racine ou un sous-domaine"
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://codeberg.org/streams/streams/archive/d6a3477f7b57e7b83468ffec59e5fdab2b0e13db.tar.gz"
        sha256 = "e308effdfa3675e6e37846ba89c9f48542027580abce6ee94b9def5a1e22ac11"

        [resources.sources.addons]
        url = "https://codeberg.org/streams/streams-addons/archive/39b1c5af9f2b1c639b6438ac85b0ea85273fc201.tar.gz"
        sha256 = "6325e08b298839a0b370f405666d040af702c31437c4e90e0472e73f84864a8f"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2-mbstring, php8.2-cli, php8.2-imagick, php8.2-xml, php8.2-zip, php8.2-curl, php8.2-ldap, php8.2-gd, mariadb-server, php8.2-mysql"

    [resources.database]
    type = "mysql"
