test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    test_upgrade_from.7d95dde09194d8948e893a92a52a02a0a48cf33e.name = "Upgrade from 23.09.28~ynh2"
    test_upgrade_from.4a60421ef85ac193294fc057480a3469f4540e41.name = "Upgrade from 23.04.10~ynh1"
    test_upgrade_from.e7681e0867203dacb0d8f86f2a81587ba012a0b1.name = "Upgrade from 23.10.10~ynh1"
