#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9253fe595bc7838590c36716d6b61c4fa42660ea.name = "Upgrade from 26.6.4~ynh2"

