test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    test_upgrade_from.77d8b627dfeb2905ff72ae693f42eff282e09e99.name = "Upgrade from 23.10.20~ynh2"
    test_upgrade_from.b95ec979addd17957566abc56e91dc0c8f81bbb3.name = "Upgrade from 23.10.24~ynh1"
