#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.636832ad7ad677af4ee374f2b7ba735bc9dac204.name = "Upgrade from 25.3.7~ynh2"
    # test_upgrade_from.00ccbbeb7e3da0209698ff12cdeb274a27f048af.name = "Upgrade from 23.11.14~ynh1"
