test_format = 1.0

[default]


    # ------------
    # Tests to run
    # ------------

    exclude = ["change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    test_upgrade_from.0b3d6c80be7fae311d1e560e24af963bb212c04f.name = "Upgrade from 23.08.14~ynh1"
    test_upgrade_from.34f7b7dfe80f67150bee2fe012fc8ccb4a1bf218.name = "Upgrade from 23.08.18~ynh1"
    test_upgrade_from.def1a2f42f7366b541978694d78086d8473563e8.name = "Upgrade from 23.08.31~ynh1"
