#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent; 
location __PATH__/ {

	alias __INSTALL_DIR__/;

	# Rewrite to front controller as default rule.
	# Note: The seemingly weird syntax is normal, see: https://trac.nginx.org/nginx/ticket/97
	try_files $uri $uri/ __PATH__/__PATH__/index.php?req=$uri&$args;
	
	client_max_body_size 50m;
	client_body_buffer_size 128k;

	# Default indexes and catch-all
	index index.php;
	charset utf-8;

	location ~* \.php$ {
		try_files $uri =404;
		fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
		include fastcgi_params_no_auth;
		fastcgi_read_timeout 300;
	}

	# Disable access to all existing dotfiles/directories except for .well-known
	# by redirecting them through the router - which will have no existing route or exception for them.
	location ^~ /.well-known/ {
		try_files $uri $uri/ __PATH__/__PATH__/index.php?req=$uri&$args;
	}

	location ~ /\. {
		try_files $uri $uri/ __PATH__/__PATH__/index.php?req=$uri&$args;
	}

	######################################################
	# Here we deny access to certain folders & files     #
	# just as in htaccess.dist and other .htaccess files #
	# in the repository (which are designed for Apache)  #
	######################################################

	# block these file types
	location ~* \.(out|log|gz|env|local|yml|yaml|dist)$ {
		deny all;
	}

	# Protect repository directory from browsing
	location ~ (^|/)\.git {
		deny all;
	}

	# Protect store and util directories from browsing
	location ~ (^|/)(store|util) {
		deny all;
	}

	# Deny access to *.tpl files in view directory
	location ~ ^/view/tpl/.*\.tpl$ {
		deny all;
	}

	######################################################
	# Here we deny access to other folders & files       #
	# no one one needs to access from the web            #
	######################################################

	# Deny access to composer related files in base directory
	location ~* ^/(compose\.|composer\.) {
		deny all;
	}

	# Deny access to files no one needs to see and don’t start with a dot
	location ~ ^/(env|phpunit\.xml) {
		deny all;
	}

	# Deny access to folders we don’t have a use for running the site
	location ~ ^/(contrib|tests) {
		deny all;
	}
}
